---

power_settings:
  macos:
    destroyfvkeyonstandby: 1 
    standbydelay: 0
    standby: 1
    womp: 0
    powernap: 0
    networkoversleep: 0
    disksleep: 10
    sleep: 0
    autopoweroffdelay: 0
    hibernatemode: 3
    autopoweroff: 1
    ttyskeepawake: 1
    displaysleep: 10
    tcpkeepalive: 1
    acwake: 0
    lidwake: 1

