---

#
# Tooling
#
- include_role: name=development


#
# MacOS
#
- block:
    - include_tasks: macos.yml
  when: distro.macos


#
# Linux
#
- block:
    - include_tasks: debian.yml
  when: distro.debian

